out/Release/v8_context_snapshot.bin                                            usr/lib/chromium
out/Release/icudtl.dat                                                         usr/lib/chromium
out/Release/libEGL.so                                                          usr/lib/chromium
out/Release/libGLESv2.so                                                       usr/lib/chromium
#out/Release/libVkICD_mock_icd.so                                               usr/lib/chromium
#out/Release/libVkLayer_khronos_validation.so                                   usr/lib/chromium
#out/Release/libvulkan.so.1                                                     usr/lib/chromium
#out/Release/swiftshader/*.so                                                   usr/lib/chromium/swiftshader
#out/Release/libvk_swiftshader.so                                               usr/lib/chromium
#out/Release/vk_swiftshader_icd.json                                            usr/lib/chromium

chrome/app/resources/manpage.1.in                                           => usr/share/man/man1/chromium.1
chrome/installer/linux/common/chromium-browser/chromium-browser.appdata.xml => usr/share/metainfo/chromium.appdata.xml
chrome/app/theme/default_100_percent/chromium/product_logo_16.png           => usr/share/icons/hicolor/16x16/apps/chromium.png
chrome/app/theme/chromium/product_logo_24.png                               => usr/share/icons/hicolor/24x24/apps/chromium.png
chrome/app/theme/default_100_percent/chromium/product_logo_32.png           => usr/share/icons/hicolor/32x32/apps/chromium.png
chrome/app/theme/chromium/product_logo_48.png                               => usr/share/icons/hicolor/48x48/apps/chromium.png
chrome/app/theme/chromium/product_logo_64.png                               => usr/share/icons/hicolor/64x64/apps/chromium.png
chrome/app/theme/chromium/product_logo_128.png                              => usr/share/icons/hicolor/128x128/apps/chromium.png
chrome/app/theme/chromium/product_logo_256.png                              => usr/share/icons/hicolor/256x256/apps/chromium.png
