#!/usr/bin/dh-exec

chrome/app/resources/manpage.1.in                                           => usr/share/man/man1/chromium.1
chrome/installer/linux/common/chromium-browser/chromium-browser.appdata.xml => usr/share/metainfo/chromium.appdata.xml
chrome/app/theme/default_100_percent/chromium/product_logo_16.png           => usr/share/icons/hicolor/16x16/apps/chromium.png
chrome/app/theme/chromium/product_logo_24.png                               => usr/share/icons/hicolor/24x24/apps/chromium.png
chrome/app/theme/default_100_percent/chromium/product_logo_32.png           => usr/share/icons/hicolor/32x32/apps/chromium.png
chrome/app/theme/chromium/product_logo_48.png                               => usr/share/icons/hicolor/48x48/apps/chromium.png
chrome/app/theme/chromium/product_logo_64.png                               => usr/share/icons/hicolor/64x64/apps/chromium.png
chrome/app/theme/chromium/product_logo_128.png                              => usr/share/icons/hicolor/128x128/apps/chromium.png
chrome/app/theme/chromium/product_logo_256.png                              => usr/share/icons/hicolor/256x256/apps/chromium.png
